phase: Phase01

model_config:
  number_of_trees: 1000
  predictors: null
  class_properties: land_cover_values

viewport:
  file_name: ../000-training-data/phase01_viewport.shp
  driver: ESRI Shapefile

training_data:
  file_name: ../000-training-data/training_data.gdb
  layer: training_points
  driver: FileGDB

assets:
  datacube:
    S1:
      - COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20180609T015452_20180609T015517_011290_014BA0_39FD
      - COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20180715T015454_20180715T015519_011815_015BE0_0362
      - COPERNICUS/S1_GRD/S1B_IW_GRDH_1SDV_20180913T015503_20180913T015528_012690_0176B4_78B3
    S2:
      DC: projects/fpca-336015/assets/williston-cba

  benchmark:
    S1:
      -
      -
    S2:
      -
      -

  dem:
